#####
name: PDPrompt

port: 6019   #  port parameters
save_root: './output/XXXX/'

# lamda weight
Adv_lamda: 1
Cyc_lamda: 5



epoch: 0        # starting epoch
n_epochs: 60       # How often do you want to display output images during training
batchSize: 1               # size of the batches

dataroot: './XXXX/XXXX/'     # root directory of the dataset
val_dataroot: './XXXX/XXXX/'

lr: 0.0001                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 1024                # size of the data crop
input_nc: 3         
output_nc: 3                  
cuda: True                
n_cpu: 1

dis:
  dim: 64                     # number of filters in the bottommost layer
  norm: none                  # normalization layer [none/bn/in/ln]
  activ: lrelu                # activation function [relu/lrelu/prelu/selu/tanh]
  n_layer: 4                  # number of layers in D
  gan_type: lsgan             # GAN loss [lsgan/nsgan/ralsgan]
  num_scales: 3               # number of scales
  pad_type: reflect           # padding type [zero/reflect]

